### ISSUE TITLE
lustre-client wants particular versions of the kernel to build against

### ISSUE THREAD

**Issue by ericvh** [arm-hpc/ohpc#19]
lustre (which provides lustre-lite which a number of packages need) requires a specific version of the kernel (which isn't currently there for aarch64)

**Comment by pawosm-arm** [comment]
can I have config.log (generated by configure script) from that failed build? Contrary to what I see in OBS logs, this package does not fail at configure step when I'm building it manually on AArch64 FC22 machine....

**Comment by ericvh** [comment]
Not sure how to pull files from failed build roots - I don't think it keeps
them around.  Have you tried using obs-build to build the package?  It
should replicate everything (including downloading the CentOS chroot).

**Comment by pawosm-arm** [comment]
With some heavy trickery I managed to read this config.log file. What I found was:

unrecognized option '-Wl,-z,relro'

It turns out something in OBS configurations sets LDFLAGS="-Wl,-z,relro" for ARMv8 builds. This is passed directly to /bin/ld which does not understand -Wl - this is gcc option which tranlates "-Wl,-z,relro" to "-z relro" when gcc invoges ld. As I never had to pass "-z relro" to my ARMv8 builds, I fixed it by adding following line to lustre.spec:
CONFIGURE_ARGS="$CONFIGURE_ARGS LDFLAGS=\"\""
before "%define eval_configure" line. This effectively wipes out content of LDFLAGS just for configure step. At least it solves this problem with 'configure'. I still want to see how this OBS is configured and where.

**Comment by pawosm-arm** [comment]
When I finally managed to build it, I faced following problem @install time:
[  979s] RPM build errors:
[  979s]     File not found: /home/abuild/rpmbuild/BUILDROOT/lustre-client-ohpc-2.8.0-15.1.aarch64/etc/init.d/lsvcgss

I believe it is caused by following lines in spec file:

%{_datadir}/lustre
%{_sysconfdir}/udev/rules.d/99-lustre.rules
%config(noreplace) %{_sysconfdir}/ldev.conf
%if 0%{?centos_version}
/etc/init.d/lsvcgss
%endif

As for now, I have no ideas what and how should be changed to have it fixed and still have CentOS compatibility maintaned.
